global: 
  scrape_interval:    10s #By default scrape interval is 5s.

scrape_configs:
  - job_name: 'orderapi'
    static_configs:
       - targets: ['orderapi:80']

  - job_name: 'productapi'
    static_configs:
       - targets: ['productapi:80']

  - job_name: 'customerapi'
    static_configs:
       - targets: ['customerapi:80']